name: "Hello Actions"
description: "Greet new gh master :)"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Vadim"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "red"
